#!/usr/bin/env python3
"""Pack home/root into fs/home_data.c and fs/home_embed.S for ramfs seed."""

import os
import sys

MYOS_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HOME = os.path.join(MYOS_ROOT, "home", "root")
OUT_C = os.path.join(MYOS_ROOT, "fs", "home_data.c")
OUT_S = os.path.join(MYOS_ROOT, "fs", "home_embed.S")


def is_elf(path):
    try:
        with open(path, "rb") as f:
            return f.read(4) == b"\x7fELF"
    except OSError:
        return False


def c_escape(data):
    out = []
    for b in data:
        if b == ord("\\"):
            out.append("\\\\")
        elif b == ord('"'):
            out.append('\\"')
        elif b == ord("\n"):
            out.append("\\n")
        elif b == ord("\r"):
            out.append("\\r")
        elif b == ord("\t"):
            out.append("\\t")
        elif 32 <= b < 127:
            out.append(chr(b))
        else:
            out.append("\\x%02x" % b)
    return "".join(out)


def sym_name(rel):
    return "home_bin_%s" % rel.replace("/", "_").replace(".", "_")


def main():
    c_lines = [
        "/* generated by tools/pack_home.py — do not edit */",
        '#include "fs.h"',
        "",
    ]
    embed_lines = [
        "/* generated by tools/pack_home.py — do not edit */",
        ".section .rodata.home_embed,\"a\",@progbits",
        ".align 1",
        "",
    ]
    seed_lines = ["void fs_load_home(void)", "{"]

    if not os.path.isdir(HOME):
        os.makedirs(HOME, exist_ok=True)

    for dirpath, _, filenames in os.walk(HOME):
        filenames.sort()
        for name in filenames:
            host = os.path.join(dirpath, name)
            rel = os.path.relpath(host, HOME).replace("\\", "/")
            vpath = "/home/root/" + rel
            exec_flag = 1 if is_elf(host) else 0
            with open(host, "rb") as f:
                data = f.read()
            if len(data) >= 16384:
                print("warning: skip %s (too large)" % host, file=sys.stderr)
                continue
            if b"\x00" in data and exec_flag:
                sym = sym_name(rel)
                incbin = os.path.relpath(host, os.path.dirname(OUT_S)).replace("\\", "/")
                c_lines.append("extern const unsigned char %s[];" % sym)
                embed_lines.append(".globl %s" % sym)
                embed_lines.append("%s:" % sym)
                embed_lines.append('    .incbin "%s"' % incbin)
                embed_lines.append("")
                seed_lines.append(
                    '    fs_seed_file("%s", (const char *)%s, %d, 0, %d);'
                    % (vpath, sym, len(data), exec_flag)
                )
            else:
                text = c_escape(data)
                seed_lines.append(
                    '    fs_seed_file("%s", "%s", %d, 0, %d);'
                    % (vpath, text, len(data), exec_flag)
                )

    seed_lines.append("}")
    seed_lines.append("")
    c_lines.extend(seed_lines)

    with open(OUT_C, "w", encoding="utf-8") as f:
        f.write("\n".join(c_lines))
    with open(OUT_S, "w", encoding="utf-8") as f:
        f.write("\n".join(embed_lines))
    print("OK:", OUT_C)
    print("OK:", OUT_S)


if __name__ == "__main__":
    main()
