/* generated by tools/pack_home.py — do not edit */
#include "fs.h"

extern const unsigned char home_bin_exec_hi[];
extern const unsigned char home_bin_file_rw[];
extern const unsigned char home_bin_fork_demo[];
extern const unsigned char home_bin_hi[];
extern const unsigned char home_bin_pagefault[];
extern const unsigned char home_bin_return0[];
extern const unsigned char home_bin_segfault_null[];
void fs_load_home(void)
{
    fs_seed_file("/home/root/exec_hi", (const char *)home_bin_exec_hi, 5920, 0, 1);
    fs_seed_file("/home/root/exec_hi.c", "#include \"user.h\"\n\nint main(void)\n{\n\twrite(1, \"exec_hi: calling execve\\n\", 24);\n\tif (execve(\"hi\") < 0) {\n\t\twrite(1, \"exec_hi: execve failed\\n\", 23);\n\t\treturn 1;\n\t}\n\twrite(1, \"exec_hi: should not reach\\n\", 27);\n\treturn 0;\n}\n", 223, 0, 0);
    fs_seed_file("/home/root/file_rw", (const char *)home_bin_file_rw, 5976, 0, 1);
    fs_seed_file("/home/root/file_rw.c", "#include \"fcntl.h\"\n#include \"user.h\"\n\nint main(void)\n{\n\tchar buf[256];\n\tint fd, n;\n\n\tfd = open(\"/home/root/hello.txt\", O_RDONLY);\n\tif (fd < 0) {\n\t\twrite(2, \"file_rw: open hello.txt failed\\n\", 32);\n\t\treturn 1;\n\t}\n\n\tn = read(fd, buf, sizeof(buf) - 1);\n\tif (n > 0) {\n\t\tbuf[n] = '\\0';\n\t\twrite(1, \"--- file_rw output ---\\n\", 23);\n\t\twrite(1, buf, n);\n\t\twrite(1, \"--- end ---\\n\", 12);\n\t}\n\tclose(fd);\n\treturn 0;\n}\n", 406, 0, 0);
    fs_seed_file("/home/root/fork_demo", (const char *)home_bin_fork_demo, 6320, 0, 1);
    fs_seed_file("/home/root/fork_demo.c", "#include \"user.h\"\n\n#define STACK_GROW_PAGES  10\n#define STACK_GROW_BYTES  (STACK_GROW_PAGES * 4096)\n\nstatic void grow_stack_pages(const char *who)\n{\n\tint i;\n\n\tprintf(\"%s: growing stack (expect store page faults)...\\n\", who);\n\tfor (i = 0; i < STACK_GROW_PAGES; i++) {\n\t\tasm volatile(\n\t\t\t\"addi sp, sp, -2048\\n\"\n\t\t\t\"addi sp, sp, -2048\\n\"\n\t\t\t\"sb   zero, 0(sp)\\n\"\n\t\t\t::: \"memory\");\n\t}\n\tprintf(\"%s: stack grow done\\n\", who);\n\tasm volatile(\n\t\t\"li   t0, %0\\n\"\n\t\t\"add  sp, sp, t0\\n\"\n\t\t:: \"i\"(STACK_GROW_BYTES) : \"t0\", \"memory\");\n}\n\nvolatile int ooxx = 222;\n\nint main(void)\n{\n\tint pid;\n\n\tgrow_stack_pages(\"parent\");\n\tpid = fork();\n\tif (pid == 0) {\n\t\tgrow_stack_pages(\"child\");\n\t\tprintf(\"child:  ooxx=%d (expect 222)\\n\", ooxx);\n\t\tooxx = 999;\n\t\tprintf(\"child:  ooxx=%d (expect 999)\\n\", ooxx);\n\t\texit(0);\n\t}\n\n\tprintf(\"parent: fork pid=%d\\n\", pid);\n\tooxx = 666;\n\tprintf(\"parent: ooxx=666 before wait (child not run yet)\\n\");\n\twaitpid(pid);\n\tprintf(\"parent: ooxx=%d after wait (expect 666)\\n\", ooxx);\n\texit(0);\n}\n", 998, 0, 0);
    fs_seed_file("/home/root/hello.sh", "#!/bin/sh\n# user script \xe2\x80\x94 test option 1 (task.md)\necho Hello from user shell script!\necho myos ramfs + sh runner OK\n", 118, 0, 0);
    fs_seed_file("/home/root/hello.txt", "Hello from /home/root/hello.txt\nThis file is read by cross-compiled user programs.\n", 83, 0, 0);
    fs_seed_file("/home/root/hi", (const char *)home_bin_hi, 5784, 0, 1);
    fs_seed_file("/home/root/hi.c", "#include \"user.h\"\n\nint main(void)\n{\n\twrite(1, \"hi from ./hi\\n\", 13);\n\treturn 0;\n}\n", 82, 0, 0);
    fs_seed_file("/home/root/pagefault", (const char *)home_bin_pagefault, 5880, 0, 1);
    fs_seed_file("/home/root/pagefault.c", "/*\n * Use more stack than exec() pre-maps; kernel demand-maps on store fault.\n */\n#include \"user.h\"\n\n#define STACK_GROW_BYTES  (20 * 4096)\n\nint main(void)\n{\n\tint i;\n\n\twrite(1, \"pagefault: using more stack than usual...\\n\", 42);\n\tfor (i = 0; i < 20; i++) {\n\t\tasm volatile(\n\t\t\t\"addi sp, sp, -2048\\n\"\n\t\t\t\"addi sp, sp, -2048\\n\"\n\t\t\t\"sb   zero, 0(sp)\\n\"\n\t\t\t::: \"memory\");\n\t}\n\twrite(1, \"pagefault: done.\\n\", 16);\n\tasm volatile(\n\t\t\"li   t0, %0\\n\"\n\t\t\"add  sp, sp, t0\\n\"\n\t\t:: \"i\"(STACK_GROW_BYTES) : \"t0\", \"memory\");\n\texit(0);\n}\n", 519, 0, 0);
    fs_seed_file("/home/root/return0", (const char *)home_bin_return0, 5744, 0, 1);
    fs_seed_file("/home/root/return0.c", "int main(void)\n{\n\treturn 0;\n}\n", 30, 0, 0);
    fs_seed_file("/home/root/segfault_null", (const char *)home_bin_segfault_null, 5800, 0, 1);
    fs_seed_file("/home/root/segfault_null.c", "#include \"user.h\"\n\nint main(void)\n{\n\tvolatile int *p = (volatile int *)0;\n\n\twrite(1, \"segfault_null: before fault\\n\", 29);\n\t*p = 1;\n\twrite(1, \"segfault_null: should not reach\\n\", 33);\n\treturn 0;\n}\n", 197, 0, 0);
    fs_seed_file("/home/root/sh01.sh", "#!/bin/bash\necho $ooxx\nooxx=999\necho $ooxx\nsleep 20\necho $ooxx\n", 63, 0, 0);
}
