/* generated by tools/pack_home.py — do not edit */
#include "fs.h"

extern const unsigned char home_bin_file_rw[];
extern const unsigned char home_bin_hi[];
extern const unsigned char home_bin_return0[];
void fs_load_home(void)
{
    fs_seed_file("/home/root/file_rw", (const char *)home_bin_file_rw, 8648, 0, 1);
    fs_seed_file("/home/root/file_rw.c", "#include \"syscall.h\"\n\n#define O_RDONLY 0\n\nstatic long syscall3(long n, long a0, long a1, long a2)\n{\n\tregister long t0 asm(\"a0\") = a0;\n\tregister long t1 asm(\"a1\") = a1;\n\tregister long t2 asm(\"a2\") = a2;\n\tregister long t7 asm(\"a7\") = n;\n\n\tasm volatile(\"ecall\"\n\t\t     : \"+r\"(t0)\n\t\t     : \"r\"(t1), \"r\"(t2), \"r\"(t7)\n\t\t     : \"memory\");\n\treturn t0;\n}\n\nstatic int open(const char *path, int flags)\n{\n\treturn (int)syscall3(SYS_open, (long)path, flags, 0);\n}\n\nstatic int read(int fd, char *buf, int len)\n{\n\treturn (int)syscall3(SYS_read, fd, (long)buf, len);\n}\n\nstatic int write(int fd, const char *buf, int len)\n{\n\treturn (int)syscall3(SYS_write, fd, (long)buf, len);\n}\n\nint main(void)\n{\n\tchar buf[256];\n\tint fd, n;\n\n\tfd = open(\"/home/root/hello.txt\", O_RDONLY);\n\tif (fd < 0) {\n\t\twrite(2, \"file_rw: open hello.txt failed\\n\", 32);\n\t\treturn 1;\n\t}\n\n\tn = read(fd, buf, sizeof(buf) - 1);\n\tif (n > 0) {\n\t\tbuf[n] = '\\0';\n\t\twrite(1, \"--- file_rw output ---\\n\", 23);\n\t\twrite(1, buf, n);\n\t\twrite(1, \"--- end ---\\n\", 12);\n\t}\n\treturn 0;\n}\n", 1019, 0, 0);
    fs_seed_file("/home/root/hello.sh", "#!/bin/sh\n# user script \xe2\x80\x94 test option 1 (task.md)\necho Hello from user shell script!\necho myos ramfs + sh runner OK\n", 118, 0, 0);
    fs_seed_file("/home/root/hello.txt", "Hello from /home/root/hello.txt\nThis file is read by cross-compiled user programs.\n", 83, 0, 0);
    fs_seed_file("/home/root/hi", (const char *)home_bin_hi, 7424, 0, 1);
    fs_seed_file("/home/root/hi.c", "#include \"syscall.h\"\n\nstatic int write(int fd, const char *buf, int len)\n{\n\tregister long t0 asm(\"a0\") = fd;\n\tregister long t1 asm(\"a1\") = (long)buf;\n\tregister long t2 asm(\"a2\") = len;\n\tregister long t7 asm(\"a7\") = SYS_write;\n\n\tasm volatile(\"ecall\" : \"+r\"(t0) : \"r\"(t1), \"r\"(t2), \"r\"(t7) : \"memory\");\n\treturn (int)t0;\n}\n\nint main(void)\n{\n\twrite(1, \"hi from ./hi\\n\", 13);\n\treturn 0;\n}\n", 384, 0, 0);
    fs_seed_file("/home/root/return0", (const char *)home_bin_return0, 6840, 0, 1);
    fs_seed_file("/home/root/return0.c", "int main(void)\n{\n\treturn 0;\n}\n", 30, 0, 0);
}
